apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: calculator-app
  labels:
    app: calculator-app
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        # Run this image
        image: us-central1-docker.pkg.dev/toturial-gcp/calculator-app/calculator-app:latest
        ports:
        - containerPort: 8501

---

apiVersion: v1
kind: Service
metadata:
  # Unique key of the Service instance
  name: calculator-app
  labels:
    app: calculator-app
spec:
  ports:
    # Accept traffic sent to port 80
    - name: http
      port: 80
      targetPort: 8501
      protocol: TCP
  selector:
    # Loadbalance traffic across Pods matching
    # this label selector
    app: calculator-app
  # Define how the Service is exposed
  # Create an HA proxy in the cloud provider
  # with an External IP address - *Only supported
  # by some cloud providers*
  type: LoadBalancer
  externalTrafficPolicy: Local