apiVersion: apps/v1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: calculator-app
  labels:
    app: calculator-app
spec:
  # 3 Pods should exist at all times.
  replicas: 2
  selector:
    matchLabels:
      app: calculator-app
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: calculator-app
    spec:
      containers:
      - name: calculator-app
        # Run this image
        image: amirweaddo/calculator_app:v1
        ports:
        - containerPort: 8501